### ISSUE TITLE
Probleme mit min/mid/max Werten

### ISSUE THREAD

**Issue by mrRobot62** [iobroker-community-adapters/ioBroker.vis-justgage#17]
Moin, ich setze die aktuelle Version ein habe aber echte Probleme.
Ich möchte das Widget als Temperature-Widget einsetzen mit Werten zw. -15 und +45. Leider klappt das nicht richtig. Mal werden mir die Werte richtig angezeigt (bei Beschriftung). Im nächsten moment steht dann wieder 0-100.....
Weiter klappt das auch irgendwie mit den Farben nicht richtig (unter Layout).

Gibt es eine Idee? Wird weiterentwickelt? Leider kann ich das Widget so nicht einsetzen obwohl ich echt cool finde.

Naja vielleicht gibt es einen Fix

**Comment by GermanBluefox** [comment]
Should be fixed with https://github.com/Pmant/ioBroker.vis-justgage/pull/25

**Comment by MK-66** [comment]
Hello GermanBluefox,
as youd said: min, mid, max was fixed in Version 1.0.1.
But unfortunately in this new version 1.0.1. all functions under Layout e.g. Farbe 2, Farbe 3, Mitte Farbe 1+2, Mitte Farbe 2+3, Haken bei kein Farbverlauf, Ende Sektor 1, Ende Sektor 2 does not work anymore, have no effect. 

All of these functions had been ok in justgage version 1.0.0 (stable rebository). Version 1.0.0 works great with js-controller 1.15.14 and vis 1.2.1, everything seems to be fine.

But with upgrade of js-conroller to 2.0.25 the problems with min, mid, max. occur in justgage version 1.0.0. So at the moment I only can use js-controller 1.15.14 and justgage version 1.0.0 and cannot update to latest versions.

I use justgage widgets in many of my views (vis version 1.2.1) and hopefully these informations are helpfull to fix the bugs soon.

**Comment by HansPeterMeier** [comment]
Ist bei mir ebenfalls, JS-Controller 2.0.29 und justgage 1.0.1.
Wenn ich die MIN oder MAX Eingaben auf eine Javascript Zahl lege und die zahl sich ändernt, dann wird das Widget nicht aktualisiert bei Min oder Max. Eine Änderung der Objektid klappt soweit noch.

**Comment by MK-66** [comment]
New Version 1.0.2 is on latest repository and everything seems to be working fine with js-controller 2.0.39. Many thanks to the developers and many thanks also for the quick reaction!

**Comment by Phillipp83** [comment]
Hallo ich habe Probleme mit den Min Max Werten. Ich habe den Js-controller 2.1.1 drauf und die Widgets ver. 1.0.2 drauf. Wenn ich die Vis. auf dem PC (chrome browser) auf mache ist alles ok (-100 - -30) . Aber auf meinem Android Handy mit dem ioBrocker.vis öffne sind die werte (0 - 100).
![PC](https://user-images.githubusercontent.com/58390332/70163342-94d87600-16bf-11ea-8619-0a068adbf29f.JPG)
![Handy Vis](https://user-images.githubusercontent.com/58390332/70163348-97d36680-16bf-11ea-8925-1f2ccafd8bb3.jpg)

**Comment by mcm1957** [comment]
please open new issue if still relevant
